### PR TITLE
New features [sync from internal repo]

### PR DESCRIPTION
**Pull request by clementfarabet**
- Makefile supports vanilla Lua (on top of LuaJIT)
- support for CURL via async.process.exec
- new fiber sleep
- new flow subpackage, provides a ratelimiter
- fixed http keepalive; now working ok
- optional code can be passed in to async.run(function() ... end)
- new process.dispatch function to execute lua code in other process
- imported url code from luasocket
- added static build (to generate .a versions of .so libs)

### CODE REVIEW

**Comment by soumith** [comment]
oh wow. features galore!!!

**Comment by clementfarabet** [comment]
yeah they've been pending for quite some time :-). In particular the http keep alive thing, I fixed a while back but realized it was still not on the public repo. We have a good http layer on top that we use quite a bit, I was about to add it to async, but [waffle](https://github.com/benglard/waffle) implements it and more, so async+waffle seems to be a nice combo to put up rest apis.

**Comment by benglard** [comment]
Looks good - thanks! I'll try and update waffle with any necessary changes once this is merged. This line still seems strange (https://github.com/clementfarabet/async/blob/0ac98bb6be299cf5c07828dd173421f854eda2b6/async/http.lua#L115), setting request.socket to itself. In the waffle websocket implementation I changed it to request.socket = client.

**Comment by clementfarabet** [comment]
Oops not sure where that came from, i removed that line. I'll merge this then, let me know if you have trouble once merged.

**Pull request merged**
